---
title: "Copper mining"
author: "Pedro Guarderas"
date: "January 15, 2018"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Copper mining}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Ordinary kriging application
Study case of copper mine.

Loading packages.
```{r,eval=TRUE,message=FALSE, warning=FALSE}
library( data.table )
library( KRIG )
library( plotly )
library( viridis )
```

Loading data.
```{r,eval=TRUE,message=FALSE, warning=FALSE}
data( 'Copper', package = 'KRIG' )
```

Processing information.
```{r,eval=TRUE,message=FALSE, warning=FALSE}
X3<-c( 100, 105 )
Dat<-Copper[ x3 >= X3[1] & x3 <= X3[2] & Z > 0, list( x1, x2, Z ) ]
Dat<-Dat[ , list( Z = mean( Z ) ), by = list( x1, x2 ) ]

X<-as.matrix( Dat[ , list( x1, x2 ) ] )

Z<-as.matrix( Dat[ , list( Z ) ] )

m<-c( 90, 90 )
x1_lim<-c( min( X[,1] ), max( X[,1] ) )
x2_lim<-c( min( X[,2] ), max( X[,2] ) )

x1_loc<-c( 100, 100 )
x2_loc<-c( 100, 100 )
x1_lim<-c( x1_lim[1] - x1_loc[1], x1_lim[2] + x1_loc[2] )
x2_lim<-c( x2_lim[1] - x2_loc[1], x2_lim[2] + x2_loc[2] )

Y1<-seq( x1_lim[1], x1_lim[2], length.out = m[1] )
Y2<-seq( x2_lim[1], x2_lim[2], length.out = m[2] )

Y<-expand.grid( Y1, Y2 )
Y<-as.matrix( Y )
```

Stablishing the kernel.
```{r,eval=TRUE,message=FALSE, warning=FALSE}
dist<-function( x, y ) {
  return( sqrt( sum( ( x - y )^2 ) ) )
}
V<-variogram( Z, X, dist, 0 )
d<-V$distance[V$sort+1,1]

spherical_variogram<-function( d, s, t ) {
  return( s - spherical_kernel( d, s, t ) )
}

s<-0.2
t<-450
FV<-sapply( d, FUN = spherical_variogram, s, t )
```

```{r,eval=TRUE,fig.show='hold', fig.show='hold', fig.align="center", fig.width=7, fig.height=4}
plot( d, V$variogram[,1], 
      cex = 0.9, pch = 16, col = 'midnightblue',
      xlab = 'd', 
      ylab = 'v' )
points( d, FV, type = 'l', col = 'olivedrab3' , lwd = 2 )
```

```{r,eval=TRUE,message=FALSE, warning=FALSE}
Kern<-function( x, y ) {
  h<-sqrt( sum( ( x - y )^2 ) )
  return( spherical_kernel( h, s, t ) )
}
```

Solving kriging problem.
```{r,eval=TRUE,message=FALSE, warning=FALSE}
K = Kov( X, X, Kern, TRUE )
k = Kov( Y, X, Kern )

KRIG<-Krig( Z = Z,
            K = K, 
            k = k,
            G = matrix( 0, 1, 1),
            g = matrix( 0, 1, 1),
            type = "simple", 
            cinv = 'syminv' )


W<-matrix( KRIG$Z, m[1], m[2] )
```

Level curves
```{r,eval=TRUE,fig.show='hold', fig.show='hold', fig.align="center", fig.width=7, fig.height=4}
cols<-terrain.colors( 40 )
plot_ly( x = Y1, y = Y2, z = W, type = "contour", colors = cols,
         contours = list( start = 0, size = 0.05, end = 1.9, showlabels = TRUE ) )
```
